[project]
name = "4Whats.net"
authors = [
    { name="hts-qatar", email="azim@htsqatar.com",},
]
description = "Awesome POS"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # Core framework apps (frappe, erpnext) are installed and managed by bench.
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# Optional dev-only dependencies can go here if needed.
[tool.bench.dev-dependencies]
# package_name = "~=1.0.0"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
erpnext = ">=15.0.0,<16.0.0"

